#ifndef DSPhysicsListMessenger_h
#define DSPhysicsListMessenger_h 1


#include "G4UImessenger.hh"
#include "G4UIcommand.hh"
#include "G4UIcmdWithABool.hh"
#include "G4UIcmdWithADouble.hh"
#include "G4UIcmdWithAnInteger.hh"
#include "globals.hh"
#include "G4UIcmdWithAString.hh"
#include "G4UIcmdWithADoubleAndUnit.hh"
#include "G4UIdirectory.hh"

using namespace std;

class DSPhysicsList;

class DSPhysicsListMessenger: public G4UImessenger {

  public:
    DSPhysicsListMessenger(DSPhysicsList*);
   ~DSPhysicsListMessenger();

    void SetNewValue(G4UIcommand*, G4String);
    
    
  private:
    
    DSPhysicsList*                fPhysicsList;
    G4UIdirectory*                fDirectory;
    G4UIcmdWithABool*             fS1S2Cmd;
    G4UIcmdWithABool*             fHPRangeCutsCmd;
    G4UIcmdWithABool*             fDepositCutsCmd;
    G4UIcmdWithAnInteger*         fOpticsCmd;
    G4UIcmdWithAString*           fHadCmd;
    G4UIcmdWithAString*           fEMCmd;
    G4UIcmdWithABool*             fKillS1S2Cmd;
    G4UIcmdWithABool*             fKillS2Cmd;
    G4UIcmdWithABool*             fKillS1Cmd;
    G4UIcmdWithADouble*           fScaleS2Cmd;
    G4UIcmdWithADoubleAndUnit*    fDriftFieldCmd;
    G4UIcmdWithADoubleAndUnit*    fExtractionFieldCmd;
    G4UIcmdWithADouble*           fThomasImelNFCmd;
    G4UIcmdWithADouble*           fThomasImelEp0Cmd;
    G4UIcmdWithADouble*           fThomasImelEp1Cmd;
    G4UIcmdWithADouble*           fDokeBirksNFp1Cmd;
    G4UIcmdWithADouble*           fDokeBirksNFp3Cmd;
    G4UIcmdWithADouble*           fDokeBirksEp1Cmd;
    G4UIcmdWithADouble*           fDokeBirksEp2Cmd;
    G4UIcmdWithADouble*           fDokeBirksEp3Cmd;
    G4UIcmdWithABool*             fTunedS1At200VCmd;

};

#endif
/*
 * $Log: DSPhysicsListMessenger.hh,v $
 * Revision 1.4  2015/04/29 14:49:17  dfranco
 * Fixed a bug in the DSGeneratorEnergyDeposit
 *
 * Revision 1.3  2014/12/22 14:40:49  dfranco
 * added the option to activate the recombination probability at 200 V/cm (/ds/physics/tunedS1); this option is by default true; selecting a specific drift field automatically switch off the tunedS1 option
 *
 * Revision 1.2  2014/07/23 14:52:38  pagnes
 * write thermal e- and kill S1 commands added
 *
 * Revision 1.1  2014/05/07 12:20:54  dfranco
 * Migration to Geant4.10.p01
 *
 * Revision 1.11  2014/01/29 13:13:42  perassos
 * Update of the electric field handling and of the Nuclear Recoils generator
 *
 * Revision 1.10  2014/01/21 10:50:53  perassos
 * Range cuts set to 1um in LAr and to 1 mm elsewhere
 *
 * Revision 1.9  2014/01/07 14:10:32  perassos
 * Added the commands to set in the macfile the electric field and the Thomas-Imel parameters
 *
 * Revision 1.8  2013/07/25 09:55:59  dfranco
 * Added a second version of NEST, still in development, and actually not working. The default version is DSLight
 *
 * Revision 1.7  2013/07/24 09:48:58  dfranco
 * Added S1 and S2 equivalent energies, the material index for each deposit, the command killS1S2 to kill photons and electrons generated by DSLight (after storing the equivalent energies)
 *
 * Revision 1.6  2013/06/10 14:15:41  dfranco
 * Added two commands: /ds/physics/killS2 and /ds/physics/scaleS2 to kill or scale the S2 light
 *
 * Revision 1.5  2013/06/03 08:35:18  dfranco
 * added command to kill the optical processes
 *
 * Revision 1.4  2013/04/18 12:55:33  dfranco
 * Added hadronic and em physics lists
 *
 * Revision 1.3  2013/04/10 21:06:07  meregaglia
 * added S1S2 from NEST and possibility to switch on or off this physics. Work in progress on the physics itsel
 *
 * Revision 1.2  2013/03/22 14:09:40  dfranco
 * Added the cvs logger code at the end of each file
 *
 */
